version: '3.6'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: globalize2_test
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
